theme = "kanagawa"

[editor]
line-number = "relative"
bufferline = "multiple"
cursorline = true
color-modes = true
popup-border = "all"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
H = ["goto_previous_buffer"]
L = ["goto_next_buffer"]
C-j = ["select_prev_sibling"]
C-k = ["select_next_sibling"]
Y = ["yank_main_selection_to_primary_clipboard"]
P = ["replace_selections_with_primary_clipboard"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true
display-inlay-hints = true
