# attribute = ""
keyword = "oniViolet"
# "keyword.directive" = "" # -- preprocessor comments (#if in C)
# namespace = ""
punctuation = "springViolet2"
# "punctuation.delimiter" = ""
operator = "boatYellow2"
# special = ""
# "variable.other.member" = ""
variable = "carpYellow"
"variable.parameter" = { modifiers = ["underlined"] }
"variable.builtin" = "waveRed"
type = "waveAqua2"
"type.builtin" = "waveAqua2" # TODO: distinguish?
# constructor = ""
function = "crystalBlue"
# "function.macro" = ""
"function.builtin" = "springBlue"
# tag = ""
comment = "fujiGray"
constant = "surimiOrange"
"constant.builtin" = "surimiOrange"
string = "springGreen"
"constant.numeric" = "surimiOrange"
"constant.character.escape" = "surimiOrange"
# used for lifetimes
# label = ""

# "markup.heading" = ""
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
# "markup.link.url" = { fg = "", modifiers = ["underlined"] }
# "markup.link.text" = ""
# "markup.raw" = ""

"diff.plus" = "autumnGreen"
"diff.minus" = "autumnRed"
"diff.delta" = "autumnYellow"

"ui.background" = { bg = "sumiInk1" }
"ui.background.separator" = { fg = "oldWhite" }
"ui.linenr" = { fg = "oldWhite" }
"ui.linenr.selected" = { fg = "oldWhite" }
"ui.statusline" = { fg = "oldWhite", bg = "sumiInk0" }
"ui.statusline.inactive" = { fg = "oldWhite", bg = "sumiInk0" }
"ui.popup" = { bg = "waveBlue1" }
"ui.window" = { fg = "oldWhite" }
"ui.help" = { bg = "waveBlue2", fg = "oldWhite" }

# "ui.text" = { fg = "" }
# "ui.text.focus" = { fg = "" }
"ui.virtual" = { fg = "fujiGray" }

"ui.virtual.indent-guide" = { fg = "fujiGray" }

"ui.selection" = { bg = "waveBlue1" }
"ui.selection.primary" = { bg = "waveBlue1" }
# "ui.cursor.select" = { bg = "" }
# "ui.cursor.insert" = { bg = "" }
# "ui.cursor.match" = { fg = "", bg = "" }
"ui.cursor" = { modifiers = ["reversed"] }
"ui.cursorline.primary" = { bg = "sumiInk3" }
# "ui.highlight" = { bg = "" }

# "ui.menu" = { fg = "", bg = "" }
# "ui.menu.selected" = { fg = "", bg = "" }
# "ui.menu.scroll" = { fg = "", bg = "" }

diagnostic = { modifiers = ["underlined"] }
"diagnostic.hint" = { fg = "dragonBlue", bg = "sumiInk1" }
"diagnostic.info" = { fg = "waveAqua1", bg = "sumiInk1" }
"diagnostic.warning" = { fg = "roninYellow", bg = "sumiInk1" }
"diagnostic.error" = { fg = "samuraiRed", bg = "sumiInk1" }

warning = "roninYellow"
error = "samuraiRed"
info = "waveAqua1"
hint = "dragonBlue"

[palette]
fujiWhite       = '#DCD7BA'   #Default foreground
oldWhite        = '#C8C093'   #Dark foreground (statuslines)
sumiInk0        = '#16161D'   #Dark background (statuslines and floating windows)
sumiInk1        = '#1F1F28'   #Default background
sumiInk2        = '#2A2A37'   #Lighter background (colorcolumn, folds)
sumiInk3        = '#363646'   #Lighter background (cursorline)
sumiInk4        = '#54546D'   #Darker foreground (line numbers, fold column, non-text characters), float borders
waveBlue1       = '#223249'   #Popup background, visual selection background
waveBlue2       = '#2D4F67'   #Popup selection background, search background
winterGreen     = '#2B3328'   #Diff Add (background)
winterYellow    = '#49443C'   #Diff Change (background)
winterRed       = '#43242B'   #Diff Deleted (background)
winterBlue      = '#252535'   #Diff Line (background)
autumnGreen     = '#76946A'   #Git Add
autumnRed       = '#C34043'   #Git Delete
autumnYellow    = '#DCA561'   #Git Change
samuraiRed      = '#E82424'   #Diagnostic Error
roninYellow     = '#FF9E3B'   #Diagnostic Warning
waveAqua1       = '#6A9589'   #Diagnostic Info
dragonBlue      = '#658594'   #Diagnostic Hint
fujiGray        = '#727169'   #Comments
springViolet1   = '#938AA9'   #Light foreground
oniViolet       = '#957FB8'   #Statements and Keywords
crystalBlue     = '#7E9CD8'   #Functions and Titles
springViolet2   = '#9CABCA'   #Brackets and punctuation
springBlue      = '#7FB4CA'   #Specials and builtin functions
lightBlue       = '#A3D4D5'   #Not used
waveAqua2       = '#7AA89F'   #Types
springGreen     = '#98BB6C'   #Strings
boatYellow1     = '#938056'   #Not used
boatYellow2     = '#C0A36E'   #Operators, RegEx
carpYellow      = '#E6C384'   #Identifiers
sakuraPink      = '#D27E99'   #Numbers
waveRed         = '#E46876'   #Standout specials 1 (builtin variables)
peachRed        = '#FF5D62'   #Standout specials 2 (exception handling, return)
surimiOrange    = '#FFA066'   #Constants, imports, booleans
